In [1]:
import numpy as np
import torch
import torchvision.transforms as transforms
from myDataset import MyDataset

data = np.load("dataset/normal/data0.npy")


In [2]:
transforms_ = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
    ])
    
def dataPreprocess(data):
    center = (320, 240)
    threshold = 0.2
    # print(data.shape)
    data = np.transpose(data)
    print("ts", data.shpae)
    np.transpose(data)[0] = np.transpose(data)[0] - center[0]
    np.transpose(data)[1] = np.transpose(data)[1] - center[1]

    max = np.amax(data, axis=0)
    # print(max)
    np.transpose(data)[0] = np.transpose(data)[0]/max[0]
    np.transpose(data)[1] = np.transpose(data)[1]/max[1]
    for i, ele in enumerate(np.transpose(data)[2]):
        if ele < threshold:
            np.transpose(data)[0][i] = 0.0
            np.transpose(data)[1][i] = 0.0
    # print('+++++++++++++++++++++++++++')
    # print(data)
    data = transforms_(data)
    print("bef", data.shape)
    data = torch.permute(data,(0, 2, 1))
    return data


print(dataPreprocess(data[6]))
print(dataPreprocess(data[6]).shape)

bef torch.Size([1, 25, 3])
tensor([[[-0.1508,  0.8312,  0.7466,  0.3535, -0.3489,  0.9714,  0.4099,
          -0.8267,  1.0000, -1.0000, -1.1630, -1.5836,  0.9439, -1.4719,
          -2.0055, -1.0000,  0.0451, -1.0000,  0.5787, -2.7351, -2.5945,
          -1.9491, -1.0000, -1.0000, -1.5004],
         [-3.0716, -2.3905, -2.4434, -1.6007, -1.6358, -2.3901, -1.3682,
          -1.5108, -0.6321, -1.0000, -0.5605,  0.8744, -0.5247, -0.4171,
           0.7841, -1.0000, -3.1432, -1.0000, -3.0535,  0.8024,  0.8739,
           0.9282, -1.0000, -1.0000,  1.0000],
         [ 0.6997,  0.2497,  0.0378, -0.3532,  0.3895,  0.5753,  0.4322,
           0.6455, -0.3375, -0.6020,  0.0214,  0.2750, -0.1917,  0.2032,
           0.1529, -0.7675,  0.7318, -1.0000,  0.7892,  0.1193,  0.1547,
          -0.1494, -0.8617, -1.0000,  0.3447]]])
bef torch.Size([1, 25, 3])
torch.Size([1, 3, 25])


In [14]:
data_list = ['normal', 'bad_leg']
mydataset = MyDataset(data_list, transform=transforms_)
count = 0
minV, maxV = 1.0, -1.0
for i in range(len(mydataset)):
    x, y = mydataset[i]
    x = x.numpy()
    mi = np.min(x)
    ma = np.max(x)
    if ma > 1.0:
        count += 1
    if mi < minV:
        minV = mi
    if ma > maxV:
        maxV = ma
        if maxV > 1.0:
            print(i)
            print(x)
            print(x[0][0])

        

print(maxV, minV)
print(count)

normal
bad_leg
(7666, 3, 25)
1.0 -1.0
0


In [15]:
mydataset = MyDataset(data_list)
x, y = mydataset[555]

normal
bad_leg
(7666, 3, 25)


In [16]:
x

array([[0.4689163 , 0.56013596, 0.578399  , 0.505412  , 0.4324508 ,
        0.5418435 , 0.4911785 , 0.3939787 , 0.55809575, 0.5824109 ,
        0.4162483 , 0.41215187, 0.5378203 , 0.3655737 , 0.3634839 ,
        0.        , 0.4769666 , 0.        , 0.51551396, 0.2845197 ,
        0.3006701 , 0.37770176, 0.37768713, 0.37977895, 0.4183195 ],
       [0.19263831, 0.29111052, 0.2856396 , 0.40878046, 0.40597072,
        0.2937678 , 0.4497916 , 0.42248893, 0.578454  , 0.5702458 ,
        0.5565386 , 0.7781594 , 0.5839388 , 0.5811608 , 0.8219217 ,
        0.        , 0.17894848, 0.        , 0.18168285, 0.8221005 ,
        0.8383796 , 0.8412228 , 0.76725113, 0.7699336 , 0.8000073 ],
       [0.7702527 , 0.65667665, 0.4607792 , 0.30980235, 0.4482065 ,
        0.740574  , 0.7560461 , 0.8391278 , 0.4186608 , 0.31011203,
        0.32257158, 0.7562249 , 0.43987882, 0.82445794, 0.75808424,
        0.        , 0.8836112 , 0.        , 0.87498915, 0.59130263,
        0.5671535 , 0.69084215, 0.11813373, 0.

In [12]:
np.max(x)

5.0

In [20]:
x = np.zeros(( 3, 25))
x.shape

(3, 25)

In [21]:
x[:][0] = 2
x[:][1] = 5

In [22]:
x

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])